<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE escritores [
    <!ELEMENT escritores (escritor*)>
    <!ELEMENT escritor ((nombre | nacimiento), (nacimiento | nombre))>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT nacimiento ANY>
]>

<escritores>
    <escritor>
        <nombre>Mario Vargas LLosa</nombre>
        <nacimiento>28 de marzo de 1936</nacimiento>
    </escritor>
    <escritor>
        <nacimiento>1 de abril de 1929</nacimiento>
        <nombre>Milan Kundera</nombre>
    </escritor>
</escritores>