<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cine [
    <!ELEMENT cine (paises, idiomas, personas, peliculas)>
    <!ELEMENT paises (pais+)>
    <!ELEMENT pais (#PCDATA)>
    <!ATTLIST pais cc ID #REQUIRED>
    <!ELEMENT idiomas (idioma+)>
    <!ELEMENT idioma (#PCDATA)>
    <!ATTLIST idioma lc ID #REQUIRED>
    <!ELEMENT personas (persona+)>
    <!ELEMENT persona (#PCDATA)>
    <!ATTLIST persona
        fecha_nacimiento CDATA #REQUIRED
        pais_nacimiento IDREF #REQUIRED>
    <!ELEMENT peliculas (pelicula+)>
    <!ELEMENT pelicula (estreno, titulo+, autores)>
    <!ELEMENT estreno (#PCDATA)>
    <!ELEMENT titulo (#PCDATA)>
    <!ATTLIST titulo idioma IDREF #REQUIRED>
    <!ELEMENT autores (#PCDATA)>
    <!ATTLIST autores
        compositor CDATA #IMPLIED
        director CDATA #REQUIRED>
]>
<cine>
    <paises>
        <pais cc="UK">Reino Unido</pais>
        <pais cc="EEUU">Estados Unidos</pais>
        <pais cc="DE">Alemania</pais>
    </paises>
    <idiomas>
        <idioma lc="EN"></idioma>
        <idioma lc="ES"></idioma>
    </idiomas>
    <personas>
        <persona fecha_nacimiento="1970" pais_nacimiento="UK">Christopher Nolan</persona>
        <persona fecha_nacimiento="1942" pais_nacimiento="EEUU">Martin Scorsese</persona>
        <persona fecha_nacimiento="1975" pais_nacimiento="EEUU">Drew Goddard</persona>
        <persona fecha_nacimiento="1957" pais_nacimiento="DE">Hans Zimmer</persona>
        <persona fecha_nacimiento="1967" pais_nacimiento="UK">David Julyan</persona>
    </personas>
    <peliculas>
        <pelicula>
            <estreno>1990</estreno>
            <titulo idioma="EN">Goodfellas</titulo>
            <titulo idioma="ES">Uno de los nuestros</titulo>
            <autores director="Martin Scorsese"></autores>
        </pelicula>
        <pelicula>
            <estreno>1991</estreno>
            <titulo idioma="EN">Thelma y Louise</titulo>
            <titulo idioma="ES">Thelma y Louise</titulo>
            <autores director="Ridley Scott" compositor="Hans Zimmer"></autores>
        </pelicula>
        <pelicula>
            <estreno>2006</estreno>
            <titulo idioma="EN">The Prestige</titulo>
            <titulo idioma="ES">El truco final</titulo>
            <autores director="Christopher Nolan" compositor="David Julyan"></autores>
        </pelicula>
        <pelicula>
            <estreno>2010</estreno>
            <titulo idioma="EN">Inception</titulo>
            <titulo idioma="ES">Origen</titulo>
            <autores director="Christopher Nolan" compositor="Hans Zimmer"></autores>
        </pelicula>
        <pelicula>
            <estreno>2011</estreno>
            <titulo idioma="EN">The Cabin in the Woods</titulo>
            <titulo idioma="ES">La caba√±a en el bosque</titulo>
            <autores director="Drew Goddard" compositor="David Julyan"></autores>
        </pelicula>
    </peliculas>
</cine>