<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cine [
    <!ELEMENT cine ((directores, peliculas) | (peliculas, directores))>
    <!ELEMENT directores (director+)>
    <!ELEMENT director EMPTY>
    <!ATTLIST director nombre CDATA >
    <!ATTLIST director fecha_nacimiento CDATA>
    <!ATTLIST director pais_nacimiento CDATA>
    <!ELEMENT peliculas (pelicula+)>
    <!ELEMENT pelicula (estreno*, titulo*, director)>
    <!ATTLIST pelicula titulo CDATA #REQUIRED>
    <!ELEMENT estreno (#PCDATA)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT director (#PCDATA)>
]>

<cine>
    <directores>
        <director nombre="Christopher Nolan" fecha_nacimiento="1970" pais_nacimiento="UK" />
        <director nombre="Martin Scorsese" fecha_nacimiento="1942" pais_nacimiento="EEUU" />
    </directores>
    <peliculas>
        <pelicula titulo="Uno de los nuestros">
            <estreno>1990</estreno>
            <titulo>Goodfellas</titulo>
            <director>Martin Scorsese</director>
        </pelicula>
        <pelicula titulo="Thelma y Louise">
            <estreno>1991</estreno>
            <titulo>Thelma and Louise</titulo>
            <director>Ridley Scott</director>
        </pelicula>
        <pelicula titulo="El truco final">
            <estreno>2006</estreno>
            <titulo>The Prestige</titulo>
            <director>Christopher Nolan</director>
        </pelicula>
    </peliculas>
</cine>